# Generated by Django 3.2.6 on 2021-11-14 15:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('boards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите название', max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Напишите описание', verbose_name='Оисание')),
                ('position', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер позиции на листе')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lists.list', verbose_name='Лист')),
                ('participants', models.ManyToManyField(blank=True, related_name='cards_participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('tags', models.ManyToManyField(blank=True, related_name='cards', to='boards.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FileInCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Загрузите файл', upload_to='card_files', verbose_name='Файл')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cards.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Файл в карточке',
                'verbose_name_plural': 'Файлы в карточках',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Напишите текст комментария', verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cards.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Напишите текст', max_length=50, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_lists', to='cards.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Чек-лист',
                'verbose_name_plural': 'Чек-листы',
            },
        ),
    ]
